# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def myPods

#  pod 'PullToRefreshKit', '~> 0.8.8'
  pod 'ESPullToRefresh'
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'PKHUD'  # 5.0.0

end

target 'FinanceOffice' do
  
  myPods

end

  # Pods for FinanceOffice
target 'FinanceOfficeTests' do

  myPods
  
end
